### ISSUE TITLE
NameError: name 'read_file' is not defined

### ISSUE THREAD

**Issue by venturaEffect** [IheanachorObinna/Whatsapp-Chat-project#1]
Hi,

Fist of all congrats for your work!

I'm trying to learn on data science working with pandas.

I'm pretty new on it and following your tutorial I already felt in the beginning with an error :D :

`_import pandas as pd
import numpy as np
import re
import dateparser
from collections import Counter
import matplotlib.pyplot as plt
plt.style.use('ggplot') 
def read_file(file):
    '''Reads Whatsapp text file into a list of strings''' 

  x = open(file,'r', encoding = 'utf-8') #Opens the text file into variable x but the variable cannot be explored yet
    y = x.read() #By now it becomes a huge chunk of string that we need to separate line by line
    content = y.splitlines() #The splitline method converts the chunk of string into a list of strings
    return content 

chat = read_file('Chat.txt')
len(chat)
------------------------------------------------------------
NameError                  Traceback (most recent call last)
<ipython-input-10-d6fd54aa0c4f> in <module>
----> 1 chat = read_file('Chat.txt')
      2 len(chat)

NameError: name 'read_file' is not defined_`

I don't understand. I have the whatsapp file saved on the same folder as Chat.txt but I get this error...

Thank you again. And really appreciate your time!

**Comment by ObinnaIheanachor** [comment]
Thank you. Apologies for the error you are facing. From what I can see, the function is not formatted appropriately. You should have this:

`def read_file(file):
    '''Reads Whatsapp text file into a list of strings''' 

    x = open(file,'r', encoding = 'utf-8') #Opens the text file into variable x but the variable cannot be explored yet
    y = x.read() #By now it becomes a huge chunk of string that we need to separate line by line
    content = y.splitlines() #The splitline method converts the chunk of string into a list of strings
    return content`

Let me know if this works.

**Comment by ObinnaIheanachor** [comment]
def read_file(file):
    '''Reads Whatsapp text file into a list of strings'''
    x = open(file,'r', encoding = 'utf-8') #Opens the text file into variable x but the variable cannot be explored yet
    y = x.read() #By now it becomes a huge chunk of string that we need to separate line by line
    content = y.splitlines() #The splitline method converts the chunk of string into a list of strings
    return content

**Comment by ObinnaIheanachor** [comment]
`
def read_file(file):
    '''Reads Whatsapp text file into a list of strings'''
    x = open(file,'r', encoding = 'utf-8') #Opens the text file into variable x but the variable cannot be explored yet
    y = x.read() #By now it becomes a huge chunk of string that we need to separate line by line
    content = y.splitlines() #The splitline method converts the chunk of string into a list of strings
    return content`

**Comment by ObinnaIheanachor** [comment]
Thank you. Apologies for the issues you are facing.

From what I can see, the formatting of the function is not correct. It should all be together with appropriate spacing.

Use this instead: https://gist.github.com/ObinnaIheanachor/c5ead7abf5b446cee8b35a21b578e1eb

**Comment by venturaEffect** [comment]
Yes!!

Thank you a lot!

**Comment by ObinnaIheanachor** [comment]
You are welcome. Let me know if you have any other issues.
